defmodule Ashcrud.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:categories, [:title], name: "categories_unique_title_index")
  end

  def down do
    drop_if_exists unique_index(:categories, [:title], name: "categories_unique_title_index")
  end
end
