defmodule Ashcrud.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:items) do
      modify :material_id, :bigint, null: true
    end
  end

  def down do
    alter table(:items) do
      modify :material_id, :uuid, null: false
    end
  end
end
