defmodule Ashcrud.Repo.Migrations.Materials do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:materials, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:materials, [:name], name: "materials_unique_name_index")

    create unique_index(:categories, [:title], name: "categories_unique_title_index")
  end

  def down do
    drop_if_exists unique_index(:categories, [:title], name: "categories_unique_title_index")

    drop_if_exists unique_index(:materials, [:name], name: "materials_unique_name_index")

    drop table(:materials)
  end
end
