defmodule Ashcrud.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:item_suppliers) do
      modify :supplier_id, :bigint
      modify :item_id, :bigint
    end
  end

  def down do
    alter table(:item_suppliers) do
      modify :item_id, :uuid
      modify :supplier_id, :uuid
    end
  end
end
