defmodule Ashcrud.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:item_suppliers, "item_suppliers_supplier_id_fkey")

    drop constraint(:item_suppliers, "item_suppliers_item_id_fkey")

    alter table(:item_suppliers) do
      modify :item_id,
             references(:items,
               column: :id,
               name: "item_suppliers_item_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :supplier_id,
             references(:suppliers,
               column: :id,
               name: "item_suppliers_supplier_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:item_suppliers, "item_suppliers_item_id_fkey")

    drop constraint(:item_suppliers, "item_suppliers_supplier_id_fkey")

    alter table(:item_suppliers) do
      modify :supplier_id,
             references(:suppliers,
               column: :id,
               name: "item_suppliers_supplier_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :item_id,
             references(:items,
               column: :id,
               name: "item_suppliers_item_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end
  end
end
