defmodule Ashcrud.Repo.Migrations.AddUserIdToItem do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:items) do
      add :user_id,
          references(:users,
            column: :id,
            name: "items_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:items, "items_user_id_fkey")

    alter table(:items) do
      remove :user_id
    end
  end
end
