defmodule Ashcrud.Repo.Migrations.CreateItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:items, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false
      add :code, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :material_id,
          references(:materials,
            column: :id,
            name: "items_material_id_fkey",
            type: :bigint,
            prefix: "public"
          ), null: false
    end

    create unique_index(:items, [:code], name: "items_unique_code_index")
  end

  def down do
    drop_if_exists unique_index(:items, [:code], name: "items_unique_code_index")

    drop constraint(:items, "items_material_id_fkey")

    drop table(:items)
  end
end
