defmodule Ashcrud.Repo.Migrations.CreateItemSuppliers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:item_suppliers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :item_id,
          references(:items,
            column: :id,
            name: "item_suppliers_item_id_fkey",
            type: :id,
            prefix: "public"
          ), null: false

      add :supplier_id,
          references(:suppliers,
            column: :id,
            name: "item_suppliers_supplier_id_fkey",
            type: :id,
            prefix: "public"
          ), null: false
    end

    create unique_index(:item_suppliers, [:item_id, :supplier_id],
             name: "item_suppliers_unique_item_supplier_index"
           )
  end

  def down do
    drop_if_exists unique_index(:item_suppliers, [:item_id, :supplier_id],
                     name: "item_suppliers_unique_item_supplier_index"
                   )

    drop constraint(:item_suppliers, "item_suppliers_item_id_fkey")

    drop constraint(:item_suppliers, "item_suppliers_supplier_id_fkey")

    drop table(:item_suppliers)
  end
end
